---

# Currently package from production is installed because stg does not have https and nr-cli verifies this
# Until this is fixed we need to clean metadata to avoid error: "Not using downloaded repomd.xml because it is older than what we have"
- name: clean metadata
  command: yum clean metadata
  when: ansible_pkg_mgr == 'yum'

- name: Download newrelic-cli installer
  get_url:
    url: https://raw.githubusercontent.com/newrelic/newrelic-cli/master/scripts/install.sh
    dest: /tmp/newrelic-cli-install.sh
    mode: '0111'

- name: Install newrelic-cli
  shell: yes | /tmp/newrelic-cli-install.sh

- name: Download custom recipe
  get_url:
    url: https://raw.githubusercontent.com/satya-nr/caos-ansible-roles/refs/heads/rhel10_log_rotate_support/caos.ansible_roles/roles/newrelic_cli/files/custom-infra-agent-recipe.yml
    dest: /tmp/custom-infra-agent-recipe.yml
    mode: '0644'

- name: Print recipe variable
  debug:
    msg: "{{ recipe }}"

- name: Print repo_endpoint variable
  debug:
    msg: "{{ repo_endpoint }}"

- name: Install agent via newrelic-cli satya2
  no_log: false
  shell: |
    echo "satya Recipe variable: {{ recipe }}"
    NEW_RELIC_DOWNLOAD_URL="http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/testing-pre-releases/satya-test/" \
    NEW_RELIC_REGION="{{ region }}" \
    NEW_RELIC_API_KEY={{ nr_api_key }} \
    NEW_RELIC_ACCOUNT_ID={{ nr_account_id }} \
    /usr/local/bin/newrelic install -n infrastructure-agent-installer --recipePath /tmp/custom-infra-agent-recipe.yml --debug -y

- name: Debug - newrelic_cli main.yml started
  debug:
    msg: "newrelic_cli main.yml execution started"