---

# Currently package from production is installed because stg does not have https and nr-cli verifies this
# Until this is fixed we need to clean metadata to avoid error: "Not using downloaded repomd.xml because it is older than what we have"
- name: clean metadata
  command: yum clean metadata
  when: ansible_pkg_mgr == 'yum'

- name: Download newrelic-cli installer
  get_url:
    url: https://raw.githubusercontent.com/newrelic/newrelic-cli/master/scripts/install.sh
    dest: /tmp/newrelic-cli-install.sh
    mode: '0111'
    force: yes

- name: Install newrelic-cli
  shell: yes | /tmp/newrelic-cli-install.sh

- name: Copy custom recipe from local files satya1
  copy:
    src: centos_rhel.yml
    dest: /tmp/centos_rhel.yml
    mode: '0644'
    force: yes
  register: copy_recipe_result

- name: Print copy result
  debug:
    var: copy_recipe_result

- name: Print recipe variable
  debug:
    msg: "{{ recipe }}"

- name: Print repo_endpoint variable
  debug:
    msg: "{{ repo_endpoint }}"

- name: Install agent via newrelic-cli satya6
  no_log: false
  shell: |
    NEW_RELIC_DOWNLOAD_URL="http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/testing-pre-releases/satya-rhel10/" \
    NEW_RELIC_REGION="{{ region }}" \
    NEW_RELIC_API_KEY={{ nr_api_key }} \
    NEW_RELIC_ACCOUNT_ID={{ nr_account_id }} \
    /usr/local/bin/newrelic install -n infrastructure-agent-installer --recipePath /tmp/centos_rhel.yml --debug -y
  register: agent_install_result

- name: Print agent install stdout
  debug:
    var: agent_install_result.stdout

- name: Print agent install stderr
  debug:
    var: agent_install_result.stderr

- name: Print agent install result (full)
  debug:
    var: agent_install_result

- name: Print all service facts after agent install
  debug:
    var: ansible_facts.services