---

# Currently package from production is installed because stg does not have https and nr-cli verifies this
# Until this is fixed we need to clean metadata to avoid error: "Not using downloaded repomd.xml because it is older than what we have"
- name: clean metadata
  command: yum clean metadata
  when: ansible_pkg_mgr == 'yum'

- name: Download newrelic-cli installer
  get_url:
    url: https://raw.githubusercontent.com/newrelic/newrelic-cli/master/scripts/install.sh
    dest: /tmp/newrelic-cli-install.sh
    mode: '0111'

- name: Install newrelic-cli testing
  shell: yes | /tmp/newrelic-cli-install.sh

- name: Copy custom recipe
  copy:
    src: custom-infra-agent-recipe.yml
    dest: /tmp/custom-infra-agent-recipe.yml

- name: Verify custom recipe content
  command: cat /tmp/custom-infra-agent-recipe.yml
  register: recipe_content

- name: Display custom recipe content
  debug:
    var: recipe_content.stdout_lines

- name: Install agent via newrelic-cli
  shell: |
    NEW_RELIC_DOWNLOAD_URL="http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/testing-pre-releases/satya-test/" \
    NEW_RELIC_REGION="{{ region }}" \
    NEW_RELIC_API_KEY={{ nr_api_key }} \
    NEW_RELIC_ACCOUNT_ID={{ nr_account_id }} \
    /usr/local/bin/newrelic install -n infrastructure-agent-installer --recipePath /tmp/custom-infra-agent-recipe.yml --debug -y > /tmp/newrelic_install.log 2>&1
  register: install_output
  ignore_errors: true

- name: Fetch installation log
  fetch:
    src: /tmp/newrelic_install.log
    dest: /tmp/
    flat: yes
  when: install_output is defined

- name: Print installation log content (testing)
  debug:
    msg: "{{ lookup('file', '/tmp/newrelic_install.log') }}"
  when: install_output is defined
